 


#ifndef ULTRASONIC_LCFG_H_
#define ULTRASONIC_LCFG_H_

#define		 ULTRASONIC1_TRIGGER_PIN	PINC0
#define		 ULTRASONIC2_TRIGGER_PIN	PINC1
#define		 ULTRASONIC3_TRIGGER_PIN	PINC2
#define		 ULTRASONIC4_TRIGGER_PIN	PINC3	



#endif /* ULTRASONIC_LCFG_H_ */