


#ifndef SEGMENTS_LCFG_H_
#define SEGMENTS_LCFG_H_

#define		SEGMENT1_A_PORT_DDR			DDRC
#define		SEGMENT1_A_PORT_PORT		PORTC
#define		SEGMENT1_A_PIN				0
#define		SEGMENT1_B_PORT_DDR			DDRC
#define		SEGMENT1_B_PORT_PORT		PORTC
#define		SEGMENT1_B_PIN				1
#define		SEGMENT1_C_PORT_DDR			DDRC
#define		SEGMENT1_C_PORT_PORT		PORTC
#define		SEGMENT1_C_PIN				2
#define		SEGMENT1_D_PORT_DDR			DDRC
#define		SEGMENT1_D_PORT_PORT		PORTC
#define		SEGMENT1_D_PIN				3
#define		SEGMENT1_E_PORT_DDR			DDRC
#define		SEGMENT1_E_PORT_PORT		PORTC
#define		SEGMENT1_E_PIN				4
#define		SEGMENT1_F_PORT_DDR			DDRC
#define		SEGMENT1_F_PORT_PORT		PORTC
#define		SEGMENT1_F_PIN				5
#define		SEGMENT1_G_PORT_DDR			DDRC
#define		SEGMENT1_G_PORT_PORT		PORTC
#define		SEGMENT1_G_PIN				6

#define		SEGMENTS1_2_PORT_DDR		DDRC
#define		SEGMENTS1_2_PORT_PORT		PORTC

#define		SEGMENTS2_2_PORT_DDR		DDRD
#define		SEGMENTS2_2_PORT_PORT		PORTD

#define		SEGMENT2_A_PORT_DDR			DDRD
#define		SEGMENT2_A_PORT_PORT		PORTD
#define		SEGMENT2_A_PIN				0
#define		SEGMENT2_B_PORT_DDR			DDRD
#define		SEGMENT2_B_PORT_PORT		PORTD
#define		SEGMENT2_B_PIN				1
#define		SEGMENT2_C_PORT_DDR			DDRD
#define		SEGMENT2_C_PORT_PORT		PORTD
#define		SEGMENT2_C_PIN				2
#define		SEGMENT2_D_PORT_DDR			DDRD
#define		SEGMENT2_D_PORT_PORT		PORTD
#define		SEGMENT2_D_PIN				3
#define		SEGMENT2_E_PORT_DDR			DDRD
#define		SEGMENT2_E_PORT_PORT		PORTD
#define		SEGMENT2_E_PIN				4
#define		SEGMENT2_F_PORT_DDR			DDRD
#define		SEGMENT2_F_PORT_PORT		PORTD
#define		SEGMENT2_F_PIN				5
#define		SEGMENT2_G_PORT_DDR			DDRD
#define		SEGMENT2_G_PORT_PORT		PORTD
#define		SEGMENT2_G_PIN				6

#define		SEGMENTS3_2_PORT_DDR		DDRA
#define		SEGMENTS3_2_PORT_PORT		PORTA

#define		SEGMENTS4_2_PORT_DDR		DDRB
#define		SEGMENTS4_2_PORT_PORT		PORTB
#define		SEGMENT4_1_DDR				DDRA
#define		SEGMENT4_1_PORT				PORTA
#define		SEGMENT4_1_PIN				6
#define		SEGMENT4_2_DDR				DDRA
#define		SEGMENT4_2_PORT				PORTA
#define		SEGMENT4_2_PIN				7


#endif /* SEGMENTS_LCFG_H_ */